# http://www.appveyor.com/docs/appveyor-yml

# Test against these versions of Io.js and Node.js.
environment:
  matrix:
    - nodejs_version: "0.10"
      npm_version: "1.4.4"
    - nodejs_version: "0.12"
      npm_version: "1.4.4"
    - nodejs_version: "4"
      npm_version: "latest"
    - nodejs_version: "6"
      npm_version: "latest"
    - nodejs_version: "7"
      npm_version: "latest"
    - nodejs_version: "8"
      npm_version: "latest"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node
  - ps: Install-Product node $env:nodejs_version
  # Typical npm stuff.
  - IF %nodejs_version% LSS 1 npm -g install npm@%npm_version%
  - IF %nodejs_version% LSS 1 set PATH=%APPDATA%\npm;%PATH%
  - set CL=-DDELAYIMP_INSECURE_WRITABLE_HOOKS
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
